import { collectionDescription, type ProductCategory, type ProductSize } from "@/lib/store-products"

export type Locale = "en" | "pt-PT" | "es-ES" | "ca" | "eu" | "gl" | "it-IT" | "fr-FR" | "de-DE" | "ru-RU" | "zh-CN" | "hi-IN" | "ar" | "he"

export type Copy = {
  nav: Record<"shop" | "collection" | "brand" | "b2b" | "support" | "cart" | "menu" | "close", string>
  hero: Record<"eyebrow" | "value" | "line" | "shop" | "brand", string>
  sections: Record<"launch" | "collectionTitle" | "collectionText" | "shopTitle" | "shopText" | "philosophyTitle" | "philosophyText" | "brandTitle" | "brandText" | "cultureTitle" | "cultureText" | "b2bTitle" | "b2bText" | "supportTitle" | "supportText" | "footerText", string>
  shop: Record<"search" | "all" | "inStock" | "lowStock" | "sortFeatured" | "sortNewest" | "sortLow" | "sortHigh" | "sortName" | "clear" | "empty" | "view" | "add" | "buy" | "related" | "productDetail" | "specs" | "shippingReturns" | "shippingNote" | "stockLow" | "stockIn" | "size" | "category" | "price" | "collection" | "material" | "finish" | "gripType" | "recommendedUse" | "mounting" | "weight" | "colors" | "stockQty", string>
  categories: Record<ProductCategory, string>
  sizes: Record<ProductSize | "all", string>
  cart: Record<"title" | "empty" | "continueShopping" | "checkout" | "remove" | "discountCode" | "apply" | "valid" | "invalid" | "subtotal" | "discount" | "vat" | "shipping" | "total" | "stockLimit" | "vatNote" | "unitPrice", string>
  checkout: Record<"title" | "customer" | "shippingAddress" | "shippingMethod" | "paymentMethod" | "review" | "confirmation" | "back" | "continue" | "payWithPaypal" | "email" | "firstName" | "lastName" | "phone" | "company" | "vatNumber" | "address1" | "address2" | "postalCode" | "city" | "country" | "standard" | "express" | "pickup" | "standardDesc" | "expressDesc" | "pickupDesc" | "free" | "paypal" | "paypalText" | "orderConfirmed" | "order" | "payment" | "nextSteps" | "nextStepsText" | "clearOrder" | "confirmed" | "paypalOrder" | "paypalCapture" | "notificationWarning", string>
  b2b: Record<"name" | "email" | "company" | "country" | "orderType" | "quantity" | "categories" | "message" | "includeCart" | "submit" | "success" | "summary" | "gyms" | "sending" | "formError", string>
  validation: Record<"email" | "firstName" | "lastName" | "address1" | "postalCode" | "city" | "country" | "name" | "company" | "orderType" | "quantity" | "categories" | "message" | "paypal" | "form", string>
  productText: Record<ProductCategory, { short: string; long: string }>
}

export const rtlLocales: Locale[] = ["ar", "he"]

export const locales: { locale: Locale; label: string }[] = [
  { locale: "en", label: "English" },
  { locale: "pt-PT", label: "Portugues" },
  { locale: "es-ES", label: "Espanol" },
  { locale: "ca", label: "Catala" },
  { locale: "eu", label: "Euskara" },
  { locale: "gl", label: "Galego" },
  { locale: "it-IT", label: "Italiano" },
  { locale: "fr-FR", label: "Francais" },
  { locale: "de-DE", label: "Deutsch" },
  { locale: "ru-RU", label: "Russkiy" },
  { locale: "zh-CN", label: "Zhongwen" },
  { locale: "hi-IN", label: "Hindi" },
  { locale: "ar", label: "Arabic" },
  { locale: "he", label: "Hebrew" },
]

const en: Copy = {
  nav: { shop: "Shop", collection: "Collection", brand: "Brand", b2b: "B2B", support: "Contact", cart: "Cart", menu: "Menu", close: "Close" },
  hero: { eyebrow: "Lynx Climbing", value: "Technical Climbing Holds for Deliberate Movement", line: "Premium resin climbing holds inspired by the Iberian lynx and Serra de Sintra granite. Technical macro holds, jugs and crimps for indoor climbing gyms, bouldering walls and route setters.", shop: "Shop collection", brand: "Explore brand" },
  sections: { launch: "Launch", collectionTitle: "Sintra Granite Collection", collectionText: "The Sintra Granite Collection includes macro climbing holds, jug holds and crimp holds inspired by the granite formations and forest shadows of Serra de Sintra.", shopTitle: "Complete Shop", shopText: "Search premium climbing holds, bouldering holds and climbing grips by size, category, stock and route-setting use. Cart, discounts and checkout use the same product data.", philosophyTitle: "Technical Philosophy", philosophyText: "Lynx Climbing creates premium technical climbing holds for indoor climbing gyms, bouldering walls and route setters. These resin climbing holds are designed for precise movement, controlled friction and route-setting versatility.", brandTitle: "Lynx Identity", brandText: "Quiet power, mineral surfaces and the focus of the Iberian lynx shape a premium climbing hold brand for technical indoor climbing holds.", cultureTitle: "Sintra and Iberian Culture", cultureText: "Granite climbing holds, climbing wall holds and climbing training holds are interpreted through a restrained Iberian design language.", b2bTitle: "B2B for Gyms and Route Setters", b2bText: "Volume orders, climbing gym holds, climbing volumes, custom batches and professional route setting supply are handled through the quote form.", supportTitle: "Support and Contact", supportText: "Contact us for resin climbing holds, technical support, custom colors, wholesale supply and professional route-setting orders.", footerText: "Lynx Climbing creates premium technical climbing holds, bouldering holds, climbing grips, macro climbing holds, crimp holds and jug holds for indoor climbing walls." },
  shop: { search: "Search name, SKU, grip, collection...", all: "All", inStock: "In stock", lowStock: "Low stock", sortFeatured: "Featured", sortNewest: "Newest", sortLow: "Price low to high", sortHigh: "Price high to low", sortName: "Name A-Z", clear: "Clear filters", empty: "No products match the current filters.", view: "View product", add: "Add to cart", buy: "Buy now", related: "Related products", productDetail: "Product detail", specs: "Technical specifications", shippingReturns: "Shipping and returns", shippingNote: "Shipping is calculated at checkout. Returns are available for unused products.", stockLow: "Low stock", stockIn: "In stock", size: "Size", category: "Category", price: "Price", collection: "Collection", material: "Material", finish: "Finish", gripType: "Grip type", recommendedUse: "Recommended use", mounting: "Mounting", weight: "Weight", colors: "Colors", stockQty: "Stock" },
  categories: { Macros: "Macros", Jugs: "Jugs", Crimps: "Crimps" },
  sizes: { all: "All", XS: "XS", S: "S", M: "M", L: "L", XL: "XL" },
  cart: { title: "Cart", empty: "Your cart is empty.", continueShopping: "Continue shopping", checkout: "Proceed to checkout", remove: "Remove", discountCode: "Discount code", apply: "Apply", valid: "Code applied", invalid: "Invalid discount code", subtotal: "Subtotal", discount: "Discount", vat: "VAT estimate", shipping: "Shipping", total: "Total", stockLimit: "Stock limit reached", vatNote: "VAT is a 23% estimate. Final tax may depend on the billing or shipping country.", unitPrice: "Unit price" },
  checkout: { title: "Checkout", customer: "Customer information", shippingAddress: "Shipping address", shippingMethod: "Shipping method", paymentMethod: "Payment method", review: "Review order", confirmation: "Confirmation", back: "Back", continue: "Continue", payWithPaypal: "Pay with PayPal", email: "Email", firstName: "First name", lastName: "Last name", phone: "Phone optional", company: "Company optional", vatNumber: "VAT number optional", address1: "Address line 1", address2: "Address line 2 optional", postalCode: "Postal code", city: "City", country: "Country", standard: "Standard shipping", express: "Express shipping", pickup: "Local pickup", standardDesc: "5-7 business days", expressDesc: "2-3 business days", pickupDesc: "Pickup from Lynx Climbing", free: "Free", paypal: "PayPal", paypalText: "PayPal is the active secure payment method. The cart remains intact until PayPal confirms payment.", orderConfirmed: "Order confirmed", order: "Order", payment: "Payment", nextSteps: "Next steps", nextStepsText: "We will prepare your paid order and contact you with fulfilment details.", clearOrder: "Continue shopping", confirmed: "Confirmed", paypalOrder: "PayPal order ID", paypalCapture: "PayPal capture ID", notificationWarning: "Payment succeeded, but the order notification email did not send. Keep the PayPal order ID visible." },
  b2b: { name: "Name", email: "Email", company: "Company/gym", country: "Country", orderType: "Order type", quantity: "Estimated quantity", categories: "Product categories", message: "Message", includeCart: "Include current cart items", submit: "Send B2B request", success: "Request sent.", summary: "Request summary", gyms: "Gyms, route setters, volume orders, custom colors and special batches.", sending: "Sending...", formError: "Message could not be sent. Please try again." },
  validation: { email: "A valid email is required", firstName: "First name is required", lastName: "Last name is required", address1: "Address is required", postalCode: "Postal code is required", city: "City is required", country: "Country is required", name: "Name is required", company: "Company/gym is required", orderType: "Order type is required", quantity: "Estimated quantity is required", categories: "Product categories are required", message: "Message is required", paypal: "Payment could not be completed. Please try again.", form: "Message could not be sent. Please try again." },
  productText: { Macros: { short: "Large granite-inspired macro hold for compression and open-hand movement.", long: "A large technical macro climbing hold with broad contact surfaces for compression, opposition and demanding indoor boulders." }, Jugs: { short: "Positive resin jug with rounded Sintra stone character.", long: "A positive jug climbing hold for recovery, control and powerful movement while keeping a restrained mineral visual language." }, Crimps: { short: "Compact granite-inspired crimp for precise movement.", long: "A small technical crimp climbing hold for hand sequences, footwork and detailed route setting." } },
}

type Patch = Partial<{ [K in keyof Copy]: Partial<Copy[K]> }>
function merge(base: Copy, patch: Patch): Copy {
  return { nav: { ...base.nav, ...patch.nav }, hero: { ...base.hero, ...patch.hero }, sections: { ...base.sections, ...patch.sections }, shop: { ...base.shop, ...patch.shop }, categories: { ...base.categories, ...patch.categories }, sizes: { ...base.sizes, ...patch.sizes }, cart: { ...base.cart, ...patch.cart }, checkout: { ...base.checkout, ...patch.checkout }, b2b: { ...base.b2b, ...patch.b2b }, validation: { ...base.validation, ...patch.validation }, productText: { ...base.productText, ...patch.productText } }
}

const pt = merge(en, {
  nav: { shop: "Loja", collection: "Colecao", brand: "Marca", support: "Contacto", cart: "Carrinho", close: "Fechar" },
  hero: { value: "Presas de Escalada Tecnicas para Movimento Preciso", line: "Presas de escalada premium em resina inspiradas no lince iberico e no granito da Serra de Sintra para boulder, paredes de escalada indoor e route setters.", shop: "Comprar colecao", brand: "Explorar marca" },
  sections: { launch: "Lancamento", collectionText: "A Sintra Granite Collection inclui macro holds, jugs e crimps inspirados nas formacoes graniticas e nas sombras da Serra de Sintra.", shopTitle: "Loja Completa", shopText: "Pesquise presas de escalada, presas para escalada indoor, presas de boulder e volumes de escalada por tamanho, categoria e stock.", philosophyTitle: "Filosofia Tecnica", philosophyText: "Presas de escalada tecnicas para boulder, paredes de escalada indoor e route setters, com friccao controlada e leitura precisa.", brandTitle: "Identidade Lynx", brandText: "O lince iberico, o granito de Sintra e uma linguagem mineral definem uma marca premium de presas tecnicas de escalada.", cultureTitle: "Sintra e Cultura Iberica", cultureText: "Presas de resina para escalada e presas para rocodromo com inspiracao na paisagem portuguesa.", b2bTitle: "B2B para Ginasios e Route Setters", b2bText: "Pedidos de volume, presas de parede de escalada, cores personalizadas e fornecimento profissional.", supportTitle: "Apoio e Contacto", supportText: "Contacte-nos para presas de escalada Portugal, suporte tecnico e encomendas profissionais.", footerText: "Lynx Climbing cria presas de escalada premium, presas para escalada indoor, presas de boulder, volumes de escalada, jugs, crimps e macros." },
  shop: { search: "Pesquisar nome, SKU, pega, colecao...", all: "Todos", inStock: "Em stock", lowStock: "Stock baixo", sortFeatured: "Destaque", sortNewest: "Mais recentes", sortLow: "Preco baixo para alto", sortHigh: "Preco alto para baixo", clear: "Limpar filtros", empty: "Nenhum produto corresponde aos filtros.", view: "Ver produto", add: "Adicionar ao carrinho", buy: "Comprar agora", productDetail: "Detalhe do produto", specs: "Especificacoes tecnicas", shippingReturns: "Envio e devolucoes", shippingNote: "Envio calculado no checkout. Devolucoes para produtos nao usados.", size: "Tamanho", category: "Categoria", price: "Preco", material: "Material", finish: "Acabamento", gripType: "Tipo de pega", recommendedUse: "Uso recomendado", mounting: "Montagem", weight: "Peso", colors: "Cores", stockQty: "Stock" },
  cart: { title: "Carrinho", empty: "O carrinho esta vazio.", continueShopping: "Continuar compras", checkout: "Prosseguir para checkout", remove: "Remover", discountCode: "Codigo de desconto", apply: "Aplicar", valid: "Codigo aplicado", invalid: "Codigo invalido", vat: "IVA estimado", shipping: "Envio", stockLimit: "Limite de stock atingido", vatNote: "O IVA e uma estimativa de 23%. O imposto final pode depender do pais.", unitPrice: "Preco unitario" },
  checkout: { customer: "Dados do cliente", shippingAddress: "Morada de envio", shippingMethod: "Metodo de envio", paymentMethod: "Metodo de pagamento", review: "Rever encomenda", back: "Voltar", continue: "Continuar", payWithPaypal: "Pagar com PayPal", firstName: "Nome", lastName: "Apelido", phone: "Telefone opcional", company: "Empresa/ginasio", address1: "Morada linha 1", postalCode: "Codigo postal", city: "Cidade", country: "Pais", standard: "Envio standard", express: "Envio expresso", pickup: "Recolha local", orderConfirmed: "Encomenda confirmada" },
  b2b: { name: "Nome", company: "Empresa/ginasio", country: "Pais", orderType: "Tipo de encomenda", quantity: "Quantidade estimada", categories: "Categorias de produto", message: "Mensagem", includeCart: "Incluir itens atuais do carrinho", submit: "Enviar pedido B2B", success: "Pedido enviado.", sending: "A enviar...", formError: "A mensagem nao pode ser enviada. Tente novamente." },
  validation: { email: "Email valido obrigatorio", firstName: "Nome obrigatorio", lastName: "Apelido obrigatorio", address1: "Morada obrigatoria", postalCode: "Codigo postal obrigatorio", city: "Cidade obrigatoria", country: "Pais obrigatorio", name: "Nome obrigatorio", company: "Empresa/ginasio obrigatoria", orderType: "Tipo de encomenda obrigatorio", quantity: "Quantidade estimada obrigatoria", categories: "Categorias obrigatorias", message: "Mensagem obrigatoria", form: "A mensagem nao pode ser enviada. Tente novamente.", paypal: "O pagamento nao pode ser concluido. Tente novamente." },
})

const es = merge(pt, { nav: { shop: "Tienda", collection: "Coleccion", support: "Contacto", cart: "Carrito", close: "Cerrar" }, hero: { value: "Presas de Escalada Tecnicas para Movimiento Preciso", line: "Presas de escalada tecnicas para rocodromos, boulder indoor y equipadores, inspiradas en el lince iberico y el granito de Sintra.", shop: "Comprar coleccion" }, sections: { shopTitle: "Tienda Completa", shopText: "Busque presas de escalada, presas de rocodromo, agarres de escalada, presas de resina y volumenes de escalada.", philosophyText: "Presas tecnicas de resina para movimiento preciso, friccion controlada y versatilidad de equipamiento.", b2bTitle: "B2B para Rocodromos y Equipadores", footerText: "Lynx Climbing crea presas de escalada premium, agarres de escalada, presas de boulder, jugs, crimps y macros." }, cart: { title: "Carrito", empty: "Tu carrito esta vacio.", checkout: "Ir al checkout" }, checkout: { firstName: "Nombre", lastName: "Apellido", country: "Pais" }, b2b: { name: "Nombre", submit: "Enviar solicitud B2B" }, validation: { form: "No se pudo enviar el mensaje. Intentalo de nuevo.", paypal: "No se pudo completar el pago. Intentalo de nuevo." } })
const ca = merge(es, { nav: { shop: "Botiga", collection: "Colleccio", support: "Contacte", cart: "Cistella" }, hero: { value: "Preses d'Escalada Tecniques per a Moviment Precis", line: "Preses d'escalada tecniques per a rocodroms, boulder indoor i route setters, inspirades en el linx iberic i el granit de Sintra.", shop: "Comprar colleccio" }, sections: { shopTitle: "Botiga Completa", shopText: "Cerqueu preses d'escalada, preses per rocodrom, preses de boulder, preses d'escalada indoor i volums d'escalada.", footerText: "Lynx Climbing crea preses d'escalada premium, preses de boulder, jugs, crimps i macros." }, cart: { title: "Cistella" } })
const eu = merge(es, { nav: { shop: "Denda", collection: "Bilduma", support: "Kontaktua", cart: "Saskia", close: "Itxi" }, hero: { value: "Eskalada Helduleku Teknikoak Mugimendu Zehatzerako", line: "Eskalada helduleku teknikoak indoor hormetarako, boulderrerako eta route setter profesionalentzat.", shop: "Erosi bilduma" }, sections: { shopTitle: "Denda Osoa", shopText: "Bilatu eskalada heldulekuak, boulder heldulekuak, rokodromorako heldulekuak eta indoor eskalada heldulekuak.", footerText: "Lynx Climbing markak premium eskalada heldulekuak, jugs, crimps eta macros sortzen ditu." }, cart: { title: "Saskia" } })
const gl = merge(es, { nav: { shop: "Tenda", collection: "Coleccion", support: "Contacto", cart: "Cesta", close: "Pechar" }, hero: { value: "Presas de Escalada Tecnicas para Movemento Preciso", line: "Presas de escalada tecnicas para rocodromos, boulder indoor e route setters, inspiradas no lince iberico e no granito de Sintra.", shop: "Mercar coleccion" }, sections: { shopTitle: "Tenda Completa", shopText: "Busque presas de escalada, presas para rocodromo, presas de boulder e presas de escalada indoor.", supportTitle: "Soporte e Contacto", supportText: "Contacta connosco para pedidos, soporte tecnico e subministracion profesional.", footerText: "Lynx Climbing crea presas de escalada premium, presas de boulder, jugs, crimps e macros." }, cart: { title: "Cesta", empty: "A tua cesta esta baleira.", checkout: "Ir ao checkout" }, b2b: { submit: "Enviar solicitude B2B" }, validation: { form: "Non se puido enviar a mensaxe. Tenta de novo.", paypal: "Non se puido completar o pago. Tenta de novo." } })
const it = merge(es, { nav: { shop: "Negozio", collection: "Collezione", support: "Contatto", cart: "Carrello", close: "Chiudi" }, hero: { value: "Prese da Arrampicata Tecniche per Movimento Preciso", shop: "Acquista collezione" }, sections: { shopTitle: "Negozio Completo", supportTitle: "Supporto e Contatto" }, cart: { title: "Carrello" } })
const fr = merge(es, { nav: { shop: "Boutique", collection: "Collection", brand: "Marque", support: "Contact", cart: "Panier", close: "Fermer" }, hero: { value: "Prises d'Escalade Techniques pour Mouvement Precis", shop: "Acheter la collection" }, sections: { shopTitle: "Boutique Complete", supportTitle: "Support et Contact" }, cart: { title: "Panier" } })
const de = merge(en, { nav: { shop: "Shop", collection: "Kollektion", brand: "Marke", support: "Kontakt", cart: "Warenkorb", menu: "Menue", close: "Schliessen" }, hero: { value: "Technische Klettergriffe fuer bewusste Bewegung", line: "Premium-Klettergriffe aus Resin, inspiriert vom iberischen Luchs und dem Granit von Sintra fuer Kletterhallen, Boulderwaende und Route Setter.", shop: "Kollektion kaufen", brand: "Marke ansehen" }, sections: { shopTitle: "Vollstaendiger Shop", shopText: "Suchen Sie Klettergriffe, Bouldergriffe, Kletterwandgriffe, Macro-Griffe, Crimps und Jugs nach Groesse, Kategorie und Lagerbestand.", philosophyTitle: "Technische Philosophie", philosophyText: "Technische Resin-Klettergriffe fuer praezise Bewegung, kontrollierte Reibung und professionelles Route Setting.", brandTitle: "Lynx-Identitaet", cultureTitle: "Sintra und iberische Kultur", b2bTitle: "B2B fuer Hallen und Route Setter", supportTitle: "Support und Kontakt", footerText: "Lynx Climbing entwickelt Premium-Klettergriffe, Bouldergriffe, Macro-Griffe, Crimps und Jugs fuer Indoor-Kletterwaende." }, shop: { clear: "Filter loeschen", view: "Produkt ansehen", add: "In den Warenkorb", buy: "Jetzt kaufen", search: "Name, SKU, Griff, Kollektion suchen..." }, cart: { title: "Warenkorb", empty: "Ihr Warenkorb ist leer.", checkout: "Zur Kasse" }, checkout: { customer: "Kundendaten", shippingAddress: "Lieferadresse", shippingMethod: "Versandart", paymentMethod: "Zahlungsart", review: "Bestellung pruefen", back: "Zurueck", continue: "Weiter", payWithPaypal: "Mit PayPal bezahlen", firstName: "Vorname", lastName: "Nachname", country: "Land" }, b2b: { submit: "B2B-Anfrage senden", success: "Anfrage gesendet.", formError: "Nachricht konnte nicht gesendet werden. Bitte erneut versuchen." }, validation: { form: "Nachricht konnte nicht gesendet werden. Bitte erneut versuchen.", paypal: "Zahlung konnte nicht abgeschlossen werden. Bitte erneut versuchen." } })
const ru = merge(en, { nav: { shop: "Magazin", collection: "Kollektsiya", brand: "Brend", support: "Kontakt", cart: "Korzina", close: "Zakryt" }, hero: { value: "Tekhnicheskie zatsepy dlya tochnogo dvizheniya", shop: "Kupit kollektsiyu" }, sections: { shopTitle: "Polnyy magazin", supportTitle: "Podderzhka i kontakt" }, cart: { title: "Korzina" }, validation: { form: "Soobshchenie ne otpravleno. Poprobuyte eshche raz." } })
const zh = merge(en, { nav: { shop: "Shangdian", collection: "Xilie", brand: "Pinpai", support: "Lianxi", cart: "Gouwuche", close: "Guanbi" }, hero: { value: "Jishu pan yan dian, wei jingzhun dongzuo er sheji", shop: "Goumai xilie" }, sections: { shopTitle: "Wanzheng shangdian", supportTitle: "Zhichi yu lianxi" }, cart: { title: "Gouwuche" }, validation: { form: "Xiaoxi wufa fasong. Qing chongshi." } })
const hi = merge(en, { nav: { shop: "Dukaan", collection: "Sangrah", brand: "Brand", support: "Sampark", cart: "Cart", close: "Band karein" }, hero: { value: "Sateek movement ke liye technical climbing holds", shop: "Sangrah khariden" }, sections: { shopTitle: "Puri dukaan", supportTitle: "Sahayata aur sampark" }, validation: { form: "Sandesh bheja nahi ja saka. Phir koshish karein." } })
const ar = merge(en, { nav: { shop: "المتجر", collection: "المجموعة", brand: "العلامة", support: "اتصال", cart: "السلة", menu: "القائمة", close: "إغلاق" }, hero: { value: "مسكات تسلق تقنية لحركة دقيقة", line: "مسكات تسلق فاخرة من الراتنج مستوحاة من الوشق الأيبيري وغرانيت سينترا لصالات التسلق والبولدرينغ.", shop: "تسوق المجموعة", brand: "استكشف العلامة" }, sections: { shopTitle: "متجر كامل", shopText: "ابحث عن مسكات تسلق، مسكات بولدرينغ، جغ، كرمب وماكرو حسب المقاس والفئة والمخزون.", philosophyTitle: "فلسفة تقنية", brandTitle: "هوية Lynx", cultureTitle: "سينترا والثقافة الأيبيرية", b2bTitle: "B2B للصالات ومصممي المسارات", supportTitle: "الدعم والاتصال", supportText: "تواصل معنا للطلبات والدعم التقني والتوريد الاحترافي.", footerText: "تصنع Lynx Climbing مسكات تسلق تقنية فاخرة للصالات والجدران الداخلية." }, cart: { title: "السلة", checkout: "الدفع" }, checkout: { payWithPaypal: "الدفع عبر PayPal" }, b2b: { submit: "إرسال طلب B2B", success: "تم إرسال الطلب.", formError: "تعذر إرسال الرسالة. حاول مرة أخرى." }, validation: { form: "تعذر إرسال الرسالة. حاول مرة أخرى.", paypal: "تعذر إكمال الدفع. حاول مرة أخرى." } })
const arFull = merge(ar, {
  shop: { search: "ابحث بالاسم أو SKU أو المسكة أو المجموعة...", all: "الكل", inStock: "متوفر", lowStock: "مخزون منخفض", sortFeatured: "مميز", sortNewest: "الأحدث", sortLow: "السعر من الأقل للأعلى", sortHigh: "السعر من الأعلى للأقل", sortName: "الاسم A-Z", clear: "مسح الفلاتر", empty: "لا توجد منتجات تطابق الفلاتر.", view: "عرض المنتج", add: "أضف للسلة", buy: "اشتر الآن", related: "منتجات ذات صلة", productDetail: "تفاصيل المنتج", specs: "المواصفات التقنية", shippingReturns: "الشحن والإر��اع", shippingNote: "يتم حساب الشحن عند الدفع. الإرجاع متاح للمنتجات غير المستخدمة.", stockLow: "مخزون منخفض", stockIn: "متوفر", size: "المقاس", category: "الفئة", price: "السعر", collection: "المجموعة", material: "المادة", finish: "التشطيب", gripType: "نوع المسكة", recommendedUse: "الاستخدام الموصى به", mounting: "التثبيت", weight: "الوزن", colors: "الألوان", stockQty: "المخزون" },
  cart: { title: "السلة", empty: "سلتك فارغة.", continueShopping: "متابعة التسوق", checkout: "الدفع", remove: "إزالة", discountCode: "رمز الخصم", apply: "تطبيق", valid: "تم تطبيق الرمز", invalid: "رمز غير صالح", subtotal: "المجموع الفرعي", discount: "الخصم", vat: "تقدير الضريبة", shipping: "الشحن", total: "الإجمالي", stockLimit: "تم بلوغ حد المخزون", vatNote: "الضريبة تقديرية بنسبة 23%. قد تختلف حسب البلد.", unitPrice: "سعر الوحدة" },
  checkout: { title: "الدفع", customer: "معلومات العميل", shippingAddress: "عنوان الشحن", shippingMethod: "طريقة الشحن", paymentMethod: "طريقة الدفع", review: "مراجعة الطلب", confirmation: "تأكيد", back: "رجوع", continue: "متابعة", payWithPaypal: "الدفع عبر PayPal", email: "البريد الإلكتروني", firstName: "الاسم", lastName: "اسم العائلة", phone: "الهاتف اختياري", company: "الشركة اختياري", vatNumber: "رقم الضريبة اختياري", address1: "العنوان 1", address2: "العنوان 2 اختياري", postalCode: "الرمز البريدي", city: "المدينة", country: "البلد", standard: "شحن عادي", express: "شحن سريع", pickup: "استلام محلي", standardDesc: "5-7 أيام عمل", expressDesc: "2-3 أيام عمل", pickupDesc: "استلام من Lynx Climbing", free: "مجاني", paypal: "PayPal", paypalText: "PayPal هو طريقة الدفع الآمنة النشطة. تبقى السلة حتى يؤكد PayPal الدفع.", orderConfirmed: "تم تأكيد الطلب", order: "الطلب", payment: "الدفع", nextSteps: "الخطوات التالية", nextStepsText: "سنجهز طلبك المدفوع ونتواصل معك بالتفاصيل.", clearOrder: "متابعة التسوق", confirmed: "مؤكد", paypalOrder: "معرف طلب PayPal", paypalCapture: "معرف تحصيل PayPal", notificationWarning: "نجح الدفع، لكن لم يتم إرسال بريد الطلب. احتفظ بمعرف PayPal." },
  b2b: { name: "الاسم", email: "البريد الإلكتروني", company: "الشركة/الصالة", country: "البلد", orderType: "نوع الطلب", quantity: "الكمية المقدرة", categories: "فئات المنتج", message: "الرسالة", includeCart: "تضمين عناصر السلة الحالية", submit: "إرسال طلب B2B", success: "تم إرسال الطلب.", summary: "ملخص الطلب", gyms: "صالات، مصممو مسارات، طلبات كمية وألوان مخصصة.", sending: "جار الإرسال...", formError: "تعذر إرسال الرسالة. حاول مرة أخرى." },
  validation: { email: "يلزم بريد إلكتروني صالح", firstName: "الاسم مطلوب", lastName: "اسم العائلة مطلوب", address1: "العنوان مطلوب", postalCode: "الرمز البريدي مطلوب", city: "المدينة مطلوبة", country: "البلد مطلوب", name: "الاسم مطلوب", company: "الشركة مطلوبة", orderType: "نوع الطلب مطلوب", quantity: "الكمية مطلوبة", categories: "الفئات مطلوبة", message: "الرسالة مطلوبة", paypal: "تعذر إكمال الدفع. حاول مرة أخرى.", form: "تعذر إرسال الرسالة. حاول مرة أخرى." },
})
const heFull = merge(en, {
  nav: { shop: "חנות", collection: "קולקציה", brand: "מותג", support: "קשר", cart: "עגלה", menu: "תפריט", close: "סגור" },
  hero: { value: "אחיזות טיפוס טכניות לתנועה מדויקת", line: "אחיזות טיפוס פרימיום מרזין בהשראת הלינקס האיברי וגרניט סינטרה לקירות בולדרינג ואולמות טיפוס.", shop: "קנה קולקציה", brand: "חקור מותג" },
  sections: { shopTitle: "חנות מלאה", shopText: "חפש אחיזות טיפוס, אחיזות בולדרינג, ג'אגים, קרימפים ומאקרו לפי מידה, קטגוריה ומלאי.", philosophyTitle: "פילוסופיה טכנית", brandTitle: "זהות Lynx", cultureTitle: "סינטרה ותרבות איברית", b2bTitle: "B2B לאולמות ולמסלולים", supportTitle: "תמיכה וקשר", supportText: "צור קשר להזמנות, תמיכה טכנית ואספקה מקצועית.", footerText: "Lynx Climbing מייצרת אחיזות טיפוס טכניות פרימיום לקירות ואולמות טיפוס." },
  shop: { search: "חפש שם, SKU, אחיזה, קולקציה...", all: "הכל", inStock: "במלאי", lowStock: "מלאי נמוך", sortFeatured: "מומלץ", sortNewest: "חדש", sortLow: "מחיר נמוך לגבוה", sortHigh: "מחיר גבוה לנמוך", sortName: "שם A-Z", clear: "נקה מסננים", empty: "אין מוצרים מתאימים.", view: "צפה במוצר", add: "הוסף לעגלה", buy: "קנה עכשיו", related: "מוצרים קשורים", productDetail: "פרטי מוצר", specs: "מפרט טכני", shippingReturns: "משלוח והחזרות", shippingNote: "המשלוח מחושב בתשלום. החזרות למוצרים שלא נעשה בהם שימוש.", stockLow: "מלאי נמוך", stockIn: "במלאי", size: "מידה", category: "קטגוריה", price: "מחיר", collection: "קולקציה", material: "חומר", finish: "גימור", gripType: "סוג אחיזה", recommendedUse: "שימוש מומלץ", mounting: "התקנה", weight: "משקל", colors: "צבעים", stockQty: "מלאי" },
  cart: { title: "עגלה", empty: "העגלה ריקה.", continueShopping: "המשך קניה", checkout: "לתשלום", remove: "הסר", discountCode: "קוד הנחה", apply: "החל", valid: "הקוד הופעל", invalid: "קוד לא תקין", subtotal: "סכום ביניים", discount: "הנחה", vat: "מע\"מ משוער", shipping: "משלוח", total: "סה\"כ", stockLimit: "הגעת למגבלת מלאי", vatNote: "המע\"מ הוא הערכה של 23%. המס הסופי עשוי להשתנות לפי מדינה.", unitPrice: "מחיר יחידה" },
  checkout: { title: "תשלום", customer: "פרטי לקוח", shippingAddress: "כתובת משלוח", shippingMethod: "שיטת משלוח", paymentMethod: "אמצעי תשלום", review: "סקירת הזמנה", confirmation: "אישור", back: "חזרה", continue: "המשך", payWithPaypal: "שלם עם PayPal", email: "אימייל", firstName: "שם פרטי", lastName: "שם משפחה", phone: "טלפון אופציונלי", company: "חברה אופציונלי", vatNumber: "מספר עוסק אופציונלי", address1: "כתובת שורה 1", address2: "כתובת שורה 2 אופציונלי", postalCode: "מיקוד", city: "עיר", country: "מדינה", standard: "משלוח רגיל", express: "משלוח מהיר", pickup: "איסוף עצמי", standardDesc: "5-7 ימי עסקים", expressDesc: "2-3 ימי עסקים", pickupDesc: "איסוף מ-Lynx Climbing", free: "חינם", paypal: "PayPal", paypalText: "PayPal הוא אמצעי התשלום המאובטח הפעיל. העגלה נשארת עד אישור PayPal.", orderConfirmed: "ההזמנה אושרה", order: "הזמנה", payment: "תשלום", nextSteps: "השלבים הבאים", nextStepsText: "נכין את ההזמנה ששולמה וניצור קשר עם פרטי המשלוח.", clearOrder: "המשך קניות", confirmed: "מאושר", paypalOrder: "מזהה הזמנת PayPal", paypalCapture: "מזהה לכידת PayPal", notificationWarning: "התשלום הצליח, אך מייל ההזמנה לא נשלח. שמור את מזהה PayPal." },
  b2b: { name: "שם", email: "אימייל", company: "חברה/אולם", country: "מדינה", orderType: "סוג הזמנה", quantity: "כמות משוערת", categories: "קטגוריות מוצר", message: "הודעה", includeCart: "כלול פריטים מהעגלה", submit: "שלח בקשת B2B", success: "הבקשה נשלחה.", summary: "סיכום בקשה", gyms: "אולמות, מעצבי מסלולים, הזמנות כמות וצבעים מותאמים.", sending: "שולח...", formError: "לא ניתן לשלוח את ההודעה. נסה שוב." },
  validation: { email: "נדרש אימייל תקין", firstName: "נדרש שם פרטי", lastName: "נדרש שם משפחה", address1: "נדרשת כתובת", postalCode: "נדרש מיקוד", city: "נדרשת עיר", country: "נדרשת מדינה", name: "נדרש שם", company: "נדרשת חברה", orderType: "נדרש סוג הזמנה", quantity: "נדרשת כמות", categories: "נדרשות קטגוריות", message: "נדרשת הודעה", paypal: "לא ניתן להשלים את התשלום. נסה שוב.", form: "לא ניתן לשלוח את ההודעה. נסה שוב." },
})

export const translations: Record<Locale, Copy> = {
  en,
  "pt-PT": pt,
  "es-ES": es,
  ca,
  eu,
  gl,
  "it-IT": it,
  "fr-FR": fr,
  "de-DE": de,
  "ru-RU": ru,
  "zh-CN": zh,
  "hi-IN": hi,
  ar: arFull,
  he: heFull,
}
