export type ProductCategory = "Crimps" | "Jugs" | "Macros"
export type ProductSize = "XS" | "S" | "M" | "L" | "XL"

export type Product = {
  id: string
  slug: string
  sku: string
  name: string
  collection: "Sintra Granite Collection"
  category: ProductCategory
  size: ProductSize
  price: number
  stockQty: number
  shortDescription: string
  longDescription: string
  material: string
  finish: string
  gripType: string
  recommendedUse: string
  mounting: string
  weight?: string
  colors: string[]
  images: string[]
  featured?: boolean
  newArrival?: boolean
  bestSeller?: boolean
}

export const collectionDescription =
  "A technical climbing hold collection inspired by the granite formations, forest shadows and restrained atmosphere of Serra de Sintra."

export const products: Product[] = [
  {
    id: "mc-01",
    slug: "lynx-sintra-macro-mc-01",
    sku: "MC-01",
    name: "Lynx Sintra Macro MC-01",
    collection: "Sintra Granite Collection",
    category: "Macros",
    size: "XL",
    price: 185,
    stockQty: 14,
    shortDescription: "XL granite-inspired compression macro for open-hand contact and statement setting.",
    longDescription: "A large-format macro shaped around Serra de Sintra granite blocks, with broad contact surfaces for compression, opposition and powerful indoor boulders.",
    material: "Climbing hold resin/composite",
    finish: "Natural granite grey textured finish",
    gripType: "Granite Compression Macro",
    recommendedUse: "Compression boulders, feature walls and premium commercial route setting.",
    mounting: "Bolt-on climbing hold. Install with appropriate climbing wall hardware.",
    weight: "1.9 kg",
    colors: ["Natural Granite Grey"],
    images: ["/products/mc-01.png"],
    featured: true,
    newArrival: true,
  },
  {
    id: "mc-02",
    slug: "lynx-sintra-macro-mc-02",
    sku: "MC-02",
    name: "Lynx Sintra Macro MC-02",
    collection: "Sintra Granite Collection",
    category: "Macros",
    size: "XL",
    price: 178,
    stockQty: 12,
    shortDescription: "Angular XL macro with broken-granite geometry for tension and compression.",
    longDescription: "An angular macro hold for route setters who need a strong visual feature and functional surfaces for compression sequences.",
    material: "Climbing hold resin/composite",
    finish: "Natural granite grey textured finish",
    gripType: "Angular Macro",
    recommendedUse: "Statement boulders, steep wall movement and compression lines.",
    mounting: "Bolt-on climbing hold. Install with appropriate climbing wall hardware.",
    weight: "1.75 kg",
    colors: ["Natural Granite Grey"],
    images: ["/products/mc-02.png"],
    featured: true,
  },
  {
    id: "jg-01",
    slug: "lynx-sintra-jug-jg-01",
    sku: "JG-01",
    name: "Lynx Sintra Jug JG-01",
    collection: "Sintra Granite Collection",
    category: "Jugs",
    size: "XL",
    price: 62,
    stockQty: 36,
    shortDescription: "XL positive jug inspired by rounded Sintra boulders.",
    longDescription: "A generous positive jug for recovery positions, control and powerful movement while keeping a restrained granite-like visual language.",
    material: "Climbing hold resin/composite",
    finish: "Natural granite grey textured finish",
    gripType: "Jug",
    recommendedUse: "Warm-up circuits, commercial routes, steep walls and recovery positions.",
    mounting: "Bolt-on climbing hold. Install with appropriate climbing wall hardware.",
    weight: "0.55 kg",
    colors: ["Natural Granite Grey"],
    images: ["/products/jg-01.png"],
    bestSeller: true,
    featured: true,
  },
  {
    id: "jg-03",
    slug: "lynx-sintra-jug-jg-03",
    sku: "JG-03",
    name: "Lynx Sintra Jug JG-03",
    collection: "Sintra Granite Collection",
    category: "Jugs",
    size: "L",
    price: 48,
    stockQty: 42,
    shortDescription: "Large positive jug with weathered stone character.",
    longDescription: "A dependable large jug for clean route-setting rhythm, warm-up movement and controlled catches.",
    material: "Climbing hold resin/composite",
    finish: "Natural granite grey textured finish",
    gripType: "Jug",
    recommendedUse: "Indoor boulders, circuits, recovery moves and warm-up routes.",
    mounting: "Bolt-on climbing hold. Install with appropriate climbing wall hardware.",
    weight: "0.38 kg",
    colors: ["Natural Granite Grey"],
    images: ["/products/jg-03.png"],
  },
  {
    id: "jg-04",
    slug: "lynx-sintra-jug-jg-04",
    sku: "JG-04",
    name: "Lynx Sintra Jug JG-04",
    collection: "Sintra Granite Collection",
    category: "Jugs",
    size: "L",
    price: 52,
    stockQty: 30,
    shortDescription: "Large compression jug for opposing-force movement.",
    longDescription: "A positive compression jug designed for secure pulling, directional tension and powerful transitions on indoor walls.",
    material: "Climbing hold resin/composite",
    finish: "Natural granite grey textured finish",
    gripType: "Compression Jug",
    recommendedUse: "Compression moves, steep wall setting and powerful transitions.",
    mounting: "Bolt-on climbing hold. Install with appropriate climbing wall hardware.",
    weight: "0.42 kg",
    colors: ["Natural Granite Grey"],
    images: ["/products/jg-04.png"],
    newArrival: true,
  },
  {
    id: "jg-06",
    slug: "lynx-sintra-jug-jg-06",
    sku: "JG-06",
    name: "Lynx Sintra Jug JG-06",
    collection: "Sintra Granite Collection",
    category: "Jugs",
    size: "M",
    price: 34,
    stockQty: 50,
    shortDescription: "Medium positive jug for reliable route-setting options.",
    longDescription: "A medium jug that supports steady hand positions without overpowering technical indoor movement.",
    material: "Climbing hold resin/composite",
    finish: "Natural granite grey textured finish",
    gripType: "Jug",
    recommendedUse: "Indoor routes, warm-up boulders and reliable directional setting.",
    mounting: "Bolt-on climbing hold. Install with appropriate climbing wall hardware.",
    weight: "0.25 kg",
    colors: ["Natural Granite Grey"],
    images: ["/products/jg-06.png"],
  },
  {
    id: "jg-07",
    slug: "lynx-sintra-jug-jg-07",
    sku: "JG-07",
    name: "Lynx Sintra Jug JG-07",
    collection: "Sintra Granite Collection",
    category: "Jugs",
    size: "M",
    price: 34,
    stockQty: 26,
    shortDescription: "Medium jug with compact weathered-rock character.",
    longDescription: "A medium positive hold for commercial circuits and controlled indoor problems.",
    material: "Climbing hold resin/composite",
    finish: "Natural granite grey textured finish",
    gripType: "Jug",
    recommendedUse: "Circuits, transitions, recovery moves and commercial route setting.",
    mounting: "Bolt-on climbing hold. Install with appropriate climbing wall hardware.",
    weight: "0.24 kg",
    colors: ["Natural Granite Grey"],
    images: ["/products/jg-07.png"],
  },
  {
    id: "jg-08",
    slug: "lynx-sintra-jug-jg-08",
    sku: "JG-08",
    name: "Lynx Sintra Jug JG-08",
    collection: "Sintra Granite Collection",
    category: "Jugs",
    size: "S",
    price: 26,
    stockQty: 60,
    shortDescription: "Small positive jug for compact movement and foothold options.",
    longDescription: "A small jug that keeps movement accessible while preserving a compact granite profile.",
    material: "Climbing hold resin/composite",
    finish: "Natural granite grey textured finish",
    gripType: "Jug",
    recommendedUse: "Indoor circuits, warm-up routes and precise positive positions.",
    mounting: "Bolt-on climbing hold. Install with appropriate climbing wall hardware.",
    weight: "0.16 kg",
    colors: ["Natural Granite Grey"],
    images: ["/products/jg-08.png"],
  },
  {
    id: "cr-05",
    slug: "lynx-sintra-crimp-cr-05",
    sku: "CR-05",
    name: "Lynx Sintra Crimp CR-05",
    collection: "Sintra Granite Collection",
    category: "Crimps",
    size: "XS",
    price: 18,
    stockQty: 80,
    shortDescription: "Compact granite-inspired crimp for precise movement.",
    longDescription: "A small technical crimp with an eroded granite feel, built for precise hand and foot placements on indoor problems.",
    material: "Climbing hold resin/composite",
    finish: "Natural granite grey textured finish",
    gripType: "Crimp",
    recommendedUse: "Technical boulders, footwork drills, training boards and route-setting detail.",
    mounting: "Bolt-on climbing hold. Install with appropriate climbing wall hardware.",
    weight: "0.08 kg",
    colors: ["Natural Granite Grey"],
    images: ["/products/cr-05.png"],
  },
  {
    id: "cr-08",
    slug: "lynx-sintra-crimp-cr-08",
    sku: "CR-08",
    name: "Lynx Sintra Crimp CR-08",
    collection: "Sintra Granite Collection",
    category: "Crimps",
    size: "XS",
    price: 18,
    stockQty: 82,
    shortDescription: "Small granite-like edge for exacting indoor movement.",
    longDescription: "A compact XS edge for technical hand sequences, footholds and low-profile setting.",
    material: "Climbing hold resin/composite",
    finish: "Natural granite grey textured finish",
    gripType: "Crimp",
    recommendedUse: "Technical hand sequences, footholds and low-profile setting.",
    mounting: "Bolt-on climbing hold. Install with appropriate climbing wall hardware.",
    weight: "0.08 kg",
    colors: ["Natural Granite Grey"],
    images: ["/products/cr-08.png"],
    newArrival: true,
  },
]

export const approvedProductImagePaths = products.flatMap((product) => product.images)
export const getProductById = (id: string) => products.find((product) => product.id === id)
export const getProductBySlug = (slug: string) => products.find((product) => product.slug === slug)
